Update fixed scripts to include recent changes
Mirantis/kubeadm-dind-cluster pull request #301
Opened 2019-03-23 00:05 UTC by morningspace

This is to address #288 and many other similar issues people reported here and there. Just the outputs generated by running `genfixed.sh` in master branch to pickup some recent changes, especially #271.

Give that quite a few people are still using the fixed scripts according to the repo doc and the released scripts haven't been updated yet. (Maybe could someday in next release:-)), I'd propose to update these fixed scripts so as to make some people lives easier...

Feel free to take review and merge if that makes sense...

2019-03-25 03:21 UTC, morningspace commented
All tests passed! FYI @ivan4th

2019-03-27 02:17 UTC, morningspace commented
Hi @ivan4th, and others, just curious any other comments regarding getting this merged... understood the fixed scripts appear to be deprecated... really hope that's merged officially so that can unblock some people's pain on using that...

2019-03-29 10:04 UTC, morningspace commented
Any comments? @ivan4th @jellonek @roberthbailey

2019-04-03 11:52 UTC, jellonek requested changes
IMO that looks quite ok. Only two minor things found.

2019-04-03 11:52 UTC, jellonek commented on fixed/dind-cluster-stable.sh
> +# Comma-separated custom network(s) for cluster nodes to join
Rest of comments (e.g. above, and the same comment in other files) is lowercase started, looks like this was manually uppercased by accident, right?

2019-04-03 11:52 UTC, jellonek commented on fixed/dind-cluster-stable.sh
> +    local IFS=','; read -ra cust_nets <<< "${DIND_CUSTOM_NETWORKS}"
Can you do that as in https://github.com/kubernetes-sigs/kubeadm-dind-cluster/blob/b4554ac24db0480626372e6382bbd24e4d280229/dind-cluster.sh#L129 ?

2019-04-04 08:11 UTC, jellonek commented
For me it looks fine now. @ivan4th can you take a look?

2019-04-04 08:56 UTC, morningspace commented
Hey @jellonek thanks for your prompt feedback! Just happen to notice your last comment a few mins ago :-) And, @ivan4th look forward your comments as well... Thx.

P.S.
I saw some of the tests run on Circle CI will fail occasionally due to an error "Address already in use". In my case, it's `test_src_master`. Did a quick check and it appears when we start port forwarding using socat, the port number has been used by other process on the same machine already. In my case, it's `0.0.0.0: 32768`. I am not sure how Circle CI run jobs and who else is using 32768. But it seems very likely to me that Circle CI is using pooled machine which has run kubeadm-dind-cluster tests previously, and it looks we do not kill the socat process after the current test is finished. Correct me if any.

Anyway, I'd say that's not what this PR is trying to address. Maybe I can create another PR to solve it.

2019-04-04 09:01 UTC, morningspace commented on fixed/dind-cluster-stable.sh
> +# Comma-separated custom network(s) for cluster nodes to join
Yeah... now I turn it back to lowercase as I realized that it looks other comments are all lowercased... just to be consistent.

2019-04-04 09:46 UTC, jellonek approved these changes

2019-04-15 13:57 UTC, mattmb commented
Is this ready to merge? I just had to rediscover/remember https://github.com/kubernetes-sigs/kubeadm-dind-cluster/pull/263 / https://github.com/kubernetes-sigs/kubeadm-dind-cluster/pull/266 from November because the fix still isn't released.

2019-04-16 00:28 UTC, morningspace commented
Yes, it's ready for merge. @ivan4th Could you please help merge? Or, anyone else has permission to merge it?

2019-05-13 04:10 UTC, cofyc commented
does this fix https://github.com/kubernetes-sigs/kubeadm-dind-cluster/issues/280?

2019-07-28 11:56 UTC, mrbobbytables commented
Closing as this project is being deprecated and retired in favor of [KinD](https://github.com/kubernetes-sigs/kind).

Please see this issue for more details:
https://github.com/kubernetes/org/issues/1016

/close

2019-07-28 11:56 UTC, closed without merging