Bugfix/fix dind image readme
Mirantis/kubeadm-dind-cluster pull request #316
Opened 2019-07-18 23:51 UTC by kwojcicki

Removed the unneeded = when exporting DIND_IMAGE and cleared up when you can or cannot use DIND_IMAGE.

2019-07-18 23:55 UTC, kwojcicki commented
I signed it

2019-07-18 23:56 UTC, kwojcicki commented
/assign @lukaszo

2019-07-19 14:01 UTC, kwojcicki commented
@lukaszo all I did was modify the README.md so I don't believe any of the tests failing are due to my changes?

2019-07-20 09:52 UTC, jellonek requested changes
Please use squash on your commits.

2019-07-20 09:52 UTC, jellonek commented on README.md
>  env variable:
Please s/env/environment/ as this was the only place where this shortcut was used in whole file

2019-07-20 09:52 UTC, jellonek commented on README.md
> +The DIND_IMAGE env variable will only work when directly running `./dind-cluster.sh up`
Please update that to:
```
Note: the DIND_IMAGE environment variable will work only with `./dind-cluster.sh` script.  It will not work with preconfigured scripts.
```

2019-07-20 21:11 UTC, kwojcicki commented
> Please use squash on your commits.

Think I squashed it correctly :D @jellonek

2019-07-20 21:11 UTC, kwojcicki commented on README.md
> +The DIND_IMAGE env variable will only work when directly running `./dind-cluster.sh up`
Fixed :)

2019-07-20 21:12 UTC, kwojcicki commented on README.md
>  env variable:
All env => environment (this ended up being the only other place that used env)

2019-07-22 09:29 UTC, jellonek approved these changes
/approve

2019-07-25 12:11 UTC, merged